plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

version = '1.0'
group = 'com.ryorama.tstp_content'

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"
    apply plugin: "dev.architectury.loom"

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        withSourcesJar()
    }

    repositories {
        maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases'
		}
        maven {
            name = 'GeckoLib'
            url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            content {
                includeGroupByRegex("software\\.bernie.*")
                includeGroup("com.eliotlash.mclib")
            }
        }
        maven {
            url 'https://maven.teamresourceful.com/repository/maven-public/'
        }
        maven { url = "https://maven.createmod.net" }
        maven {
            url "https://cursemaven.com"
        }
        maven {
            name = "Valkyrien Skies Internal"
            url = 'https://maven.valkyrienskies.org'
        }
        maven {
            name = 'Kotlin for Forge'
            url = 'https://thedarkcolour.github.io/KotlinForForge/'
        }
        maven {
            url "https://maven.tterrag.com/"
        }
        maven { url "https://maven.shedaniel.me/" }
        maven {
            url = "https://maven.theillusivec4.top/"
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
        maven {
            name "Modding Legacy Maven"
            url "https://maven.moddinglegacy.com/maven"
        }
        maven {
            url = "https://maven.realrobotix.me/master/"
        }
        maven {
            name = "Illusive Soulworks maven"
            url = "https://maven.theillusivec4.top/"
        }
        maven { url = "https://maven.bawnorton.com/releases" }
        maven { url = "https://maven.su5ed.dev/releases" }
        mavenLocal()
    }

    dependencies {
        minecraft "com.mojang:minecraft:$project.minecraft_version"
    }
}


def generatedResources = file("src/generated/resources")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    silentMojangMappingsLicense()
    runs {
        client {
            client()
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
        server {
            server()
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
        data {
            data()
            programArgs "--all", "--mod", mod_id
            programArgs "--output", generatedResources.absolutePath
        }
        configureEach {
            property "mixin.debug", "true"
            property "mixin.debug.export.decompile", "false"
            property "mixin.debug.verbose", "true"
            property "mixin.dumpTargetOnFailure", "true"
            property "mixin.checks", "true"
            property "mixin.hotSwap", "true"
        }
    }
}
    
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
    options.release = 21
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

repositories {
    flatDir {
        dirs 'libs'
    }

}
dependencies {
    neoForge "net.neoforged:neoforge:$project.neoforge_version"
    mappings loom.officialMojangMappings()

    modImplementation("net.pixelbank.burnt:burnt:1.9.0.3")
    modImplementation("org.sinytra:connector:2.0.0-beta.7+1.21.1")
    modImplementation("org.sinytra.forgified-fabric-api:forgified-fabric-api:0.115.6+2.1.1+1.21.1")
    modImplementation("com.tiviacz.pizzadelight:pizzadelight:2.0.1")

    modImplementation('curse.maven:refurbished-furniture-897116:6623948')
    modImplementation('curse.maven:geckolib-388172:6659026')
    modImplementation('curse.maven:ballistix-443915:6791729')
    modImplementation('curse.maven:electrodynamics-316867:6792255')
    modImplementation('curse.maven:nuclear-science-318646:6785829')
    modImplementation('curse.maven:framework-549225:6531439')
    modImplementation('curse.maven:potionsmaster-356801:6826199')
    modImplementation('curse.maven:cuisine-delight-893541:6677783')
    modImplementation('curse.maven:farmers-delight-398521:6597295')
    modImplementation('curse.maven:architectury-api-419699:5786327')
    modImplementation('curse.maven:butchery-973620:6668101')
    modImplementation('curse.maven:randomium-ore-523013:6659375')
    modImplementation('curse.maven:configuration-444699:6779573')
    modImplementation('curse.maven:deeperdarker-659011:6463247')
    //modImplementation('curse.maven:haunted-harvest-541753:6759795')
    modImplementation('curse.maven:mekanism-268560:6486993')
    modImplementation('curse.maven:easy-villagers-400514:6831416')
    modImplementation('curse.maven:ato-405593:6799475')
    modImplementation('curse.maven:aether-255308:6389857')
    modImplementation('curse.maven:the-twilight-forest-227639:6472889')
    modImplementation('curse.maven:astral-dimension-645743:6821091')
    modImplementation('curse.maven:the-undergarden-379849:6687578')
    modImplementation('curse.maven:thirst-was-taken-679270:6759289')
    modImplementation('curse.maven:ex-deorum-901420:6614749')
    modImplementation('curse.maven:cloth-config-348521:5729127')
    modImplementation('curse.maven:ftb-quests-forge-289412:6829025')
    modImplementation('curse.maven:ftb-library-forge-404465:6807431')

    //Fabric mods
    runtimeOnly(project("mod-bridge"))
    api(include(project("mod-bridge"))) { transitive = false }
    implementation(project("mod-bridge")) { targetConfiguration = "modRuntimeClasspathMainMapped" }

    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:0.2.0"))
    implementation(include("com.github.bawnorton.mixinsquared:mixinsquared-forge:0.2.0"))
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}