plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
    id "com.github.johnrengelman.shadow" version '7.1.2'
    id 'org.sinytra.adapter.userdev' version '1.2.1-SNAPSHOT'
}

version = 1.0
group = mod_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neoforge_version
    accessTransformers {
        file('src/main/resources/META-INF/accesstransformer.cfg')
    }
    parchment {
        mappingsVersion = parchment_mappings_version
        minecraftVersion = minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${overhaulcraft}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    maven { url 'https://maven.minecraftforge.net/' }
    maven { url 'https://maven.neoforged.net/releases' }
    maven { url "https://maven.blamejared.com/"  }
    maven { url "https://modmaven.dev" }
    maven { url "https://maven.ithundxr.dev/snapshots" }
    maven { url "https://maven.teamresourceful.com/repository/maven-public/" }
    maven { url "https://maven.createmod.net" }
    maven { url "https://cursemaven.com" }
    maven { url "https://thedarkcolour.github.io/KotlinForForge/"  }
    maven { url "https://maven.tterrag.com/" }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.theillusivec4.top/" }
    maven { url "https://maven.moddinglegacy.com/maven" }
    maven { url "https://maven.realrobotix.me/master/" }
    maven { url "https://maven.theillusivec4.top/" }
    maven { url "https://maven.wispforest.io" }
    maven { url "https://maven.bawnorton.com/releases" }
    maven { url "https://maven.sinytra.org/" }
    maven { url "https://jitpack.io" }
    maven { url "https://maven.confluence.ink/releases" }
    maven { url "https://maven.impactdev.net/repository/development/" }
    maven { url "https://maven.digitalunderworlds.com/snapshots/" }
    maven { url "https://maven.teamabnormals.com" }
    maven { url "https://chocolateminecraft.com/maven" }
    maven { url "https://maven.wispforest.io" }
    maven { url "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"}
    maven { url "https://maven.ryanhcode.dev/releases"}
    maven { url "https://maven.terraformersmc.com/" }
    maven {
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    additionalRuntimeClasspath "org.sinytra:connector:2.0.0-beta.9+1.21.1"
    runtimeOnly "org.sinytra.forgified-fabric-api:forgified-fabric-api:0.116.7+2.2.4+1.21.1"

    implementation("com.github.thedarkcolour:ModKit:4f83c92767")
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    compileOnly("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")
    compileOnly("org.confluence.mod:ConfluenceOtherworld:${confluence_version}")
    compileOnly("org.confluence.lib:Confluence-Magic-Lib:${confluence_lib_version}")
    compileOnly("org.confluence:TerraEntity:${terra_entity_version}")
    compileOnly("org.confluence:TerraFurniture:${minecraft_version}-${terra_furniture_version}")
    compileOnly("org.confluence:TerraGuns:${minecraft_version}-${terra_guns_version}")
    compileOnly("org.confluence:TerraEntity:${terra_entity_version}")
    compileOnly("org.confluence:TerraCurio:${terra_curio_version}")
    compileOnly("com.xiaohunao:xhn_lib:1.21.1-${xhn_lib_version}")
    compileOnly("com.github.glitchfiend:TerraBlender-neoforge:${minecraft_version}-${terrablender_version}")
    compileOnly("nowebsite.makertechno:TheTrackers:${minecraft_version}-${trackers_version}")
    compileOnly("org.mesdag:ParticleStorm:${particle_storm_version}")
    compileOnly("org.mesdag.thr_dim_particle:ThreeDimensionParticle-core:${tdpc_version}")
    compileOnly("com.cobblemon:neoforge:${cobblemon_version}")
    compileOnly("maven.modrinth:protomanlys-weather:${pmweather_ver}-alpha")
    compileOnly("net.nullved:pmweatherapi:${pmweatherapi_ver}")
    compileOnly("xaero.lib:xaerolib-neoforge-1.21.1:${xaerolib_version}")
    compileOnly("io.wispforest:accessories-neoforge:${accessories_version}")
    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    compileOnly("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:21.1.3")
    compileOnly("dev.ryanhcode.sable:sable-common-1.21.1:${sable_version}")
    compileOnly("com.terraformersmc:biolith-neoforge:${biolith_version}")
    //implementation files("../AlexsCaves/build/libs/alexscaves-2.0.2.jar")

    implementation('curse.maven:architectury-api-419699:5786327')
    implementation('curse.maven:configuration-444699:6779573')
    implementation('curse.maven:ato-405593:7825464')
    implementation('curse.maven:mekanism-268560:6895130')
    compileOnly('curse.maven:randomium-ore-523013:6659375')
    compileOnly('curse.maven:framework-549225:6531439')
    compileOnly('curse.maven:refurbished-furniture-897116:6623948')
    compileOnly('curse.maven:potionsmaster-356801:6826199')
    compileOnly('curse.maven:cuisine-delight-893541:6677783')
    compileOnly('curse.maven:farmers-delight-398521:6597295')
    compileOnly('curse.maven:butchery-973620:6668101')
    compileOnly('curse.maven:deeperdarker-659011:7940538')
    compileOnly('curse.maven:easy-villagers-400514:6831416')
    compileOnly('curse.maven:aether-255308:6389857')
    compileOnly('curse.maven:the-twilight-forest-227639:6472889')
    compileOnly('curse.maven:the-undergarden-379849:7367597')
    compileOnly('curse.maven:thirst-was-taken-679270:7017923')
    compileOnly('curse.maven:ex-deorum-901420:6614749')
    compileOnly('curse.maven:cloth-config-348521:5729127')
    compileOnly('curse.maven:ftb-quests-forge-289412:6829025')
    compileOnly('curse.maven:ftb-library-forge-404465:6807431')
    compileOnly('curse.maven:melody-938643:5453382')
    compileOnly('curse.maven:confluence-dimension-patch-1308724:7523135')
    compileOnly('curse.maven:mca-535291:7702565')
    compileOnly('curse.maven:vista-1368607:7947609')
    compileOnly('curse.maven:galosphere-631098:7382684')
    compileOnly('curse.maven:citadel-331936:7476597')
    compileOnly('curse.maven:selene-499980:7943878')
    compileOnly('maven.modrinth:pizzadelight:1.21.1-2.0.2')
    compileOnly('maven.modrinth:eas-addon:0.16.4-serverfix')
    compileOnly('maven.modrinth:moonlight:1.21.1-3.0.14')
    compileOnly('maven.modrinth:supplementaries:1.21.1-3.6.5')
    compileOnly('maven.modrinth:copycats:3.0.4+mc.1.21.1-neoforge')
    compileOnly('maven.modrinth:integrated-api:1.7.3+1.21.1-neoforge')
    compileOnly('maven.modrinth:sable-true-impact:1.1.0-gamma')
    compileOnly('maven.modrinth:infinite-dimensions:2.7.1+1.21.1-neoforge')
    compileOnly('maven.modrinth:enderio:Tfs8aJPH')
    compileOnly('curse.maven:atmospheric-362393:7119609')
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
    implementation("com.teamabnormals:blueprint:${blueprint_version}")


    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:0.3.7-beta.1"))
    implementation(jarJar("com.github.bawnorton.mixinsquared:mixinsquared-neoforge:0.3.7-beta.1")) {
        version {
            strictly '[0.3.7-beta.1,)'
            prefer '0.3.7-beta.1'
        }
    }
    implementation(jarJar("com.moulberry:mixinconstraints:1.1.0")) {
        version {
            strictly '[1.1.0,)'
            prefer '1.1.0'
        }
    }
    jarJar(api("dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:${sable_companion_version}")) {
        version {
            prefer sable_companion_version
        }
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}