org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

loom.platform=neoforge

mod_id=overhaulcraft

minecraft_version=1.21.1
neoforge_version=21.1.228
parchment_mappings_version=2024.11.17
jei_version=19.19.0.219
create_version=6.0.10-280
registrate_version=MC1.21-1.3.0+67
flywheel_version=1.0.6
ponder_version=1.0.82
geckolib_version=4.7.6
terrablender_version=4.1.0.8
confluence_version=1.2.3-260213
confluence_lib_version=0.0.8
confluence_dimension_version=1.1.5-250809
terra_entity_version=1.2.1
heaven_destiny_moment_version=0.0.1
xhn_lib_version=0.0.2
vertigo_version=1.1.7-MC1.21.1
trackers_version=0.2.5
terra_guns_version=1.0
terra_furniture_version=0.0.5
terra_curio_version=1.2.0
particle_storm_version=1.1.4.3
tdpc_version=1.0.5
cobblemon_version=1.7.3+1.21.1
pmweather_ver=0.16.4
pmweatherapi_ver=0.16.4.1
blueprint_version=1.21.1-8.0.7
xaerolib_version=1.0.45
owo_version=0.12.15.4+1.21
accessories_version=1.1.0-beta.53+1.21.1
sable_version=1.2.2
vs_maven_url=
vs_maven_username=
vs_maven_password=