modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tstp_content"
version="1.0.0"
displayName="Overhaul Compat"
displayURL=""
credits=""
authors="Ryorama"
description="Custom Content and Compat for The Minecraft: Overhaul/OverhaulCraft pack"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tstp_content]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



