modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tstp_content"
version="1.0.0"
displayName="Overhaul Compat"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/overhaulcraft-compat"
credits='''
The developers of all mods used
thevortex for help with custom ore sight potions
'''
authors="Ryorama"
description="Custom Content and Compat for OverhaulCraft pack"

[[dependencies.tstp_content]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.tstp_content]]
    modId = "configuration"
    mandatory = true
    versionRange = "[2.2.0,)"
    ordering = "AFTER"
    side = "BOTH"


