modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tstp_content"
version="1.0.0"
displayName="Overhaul Compat"
displayURL=""
credits='''
The people behind the Forge modloader
The developers of all mods used
The developer of the classic TerraMine mod for various block textures
thevortex for help with custom ore sight potions
'''
authors="Ryorama"
description="Custom Content and Compat for The Minecraft: Overhaul/OverhaulCraft pack"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tstp_content]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



