modLoader="javafml"
loaderVersion="[3,)"
license = "Insert License Here"

[[mods]]
modId="overhaulcraft"
displayName="OverhaulCraft Compat"
version="1.0"
authors="Ryorama"
description='''Small things, improving Minecraft bit by bit.'''
credits ='''
The developers of all mods used
thevortex for help with custom ore sight potions
'''
[[mixins]]
config="overhaulcraft.mixins.json"

[[dependencies.overhaulcraft]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.10,)"
    ordering="NONE"
    side="BOTH"