modLoader="javafml"
loaderVersion="[3,)"
license = "Insert License Here"

[[mods]]
modId="overhaulcraft"
displayName="OverhaulCraft Compat"
version="1.0"
authors="Ryorama"
description='''The core mod for the Minecraft: Overhaul modpack.'''
credits ='''
The developers for some bits of code used
 - sbom_xela | Alex Mod Guy
thevortex for help with custom ore sight potions
'''
[[mixins]]
config="overhaulcraft.mixins.json"

[[dependencies.overhaulcraft]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.10,)"
    ordering="NONE"
    side="BOTH"