plugins {
    id("dev.architectury.loom")
}

repositories {
    flatDir {
        String root = parent.projectDir;
        dirs root.concat("/libs")
    }
}

dependencies {
    mappings(loom.officialMojangMappings())
    modImplementation("curse.maven:solar-apocalypse-refabricated-480660:5917969")
}